server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:notify_db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.mail.ru
    username: system@mbc-studio.ru
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
