server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:users
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
